package com.example.ekacareassignment.core.utils

const val NAME: String = "Name"
const val DOB_FORMAT: String = "dd/MM/yyyy"
const val AGE: String = "Age"
const val ADDRESS: String = "Address"
const val SELECT_DATE: String = "Select Date"
const val DOB: String = "Date of Birth"
const val OK: String = "OK"
const val CANCEL: String = "Cancel"
const val SUBMIT: String = "Submit"
const val TOTAL_ENTRIES: String = "Total entries"
const val USER_INFORMATION_SAVED_SUCCESSFULLY: String = "User information saved successfully"
const val NAME_CANNOT_BE_EMPTY: String = "Name cannot be empty"
const val AGE_MUST_BE_A_VALID_POSITIVE_NUMBER: String = "Age must be a valid positive number"
const val DATE_OF_BIRTH_CANNOT_BE_EMPTY: String = "Date of birth cannot be empty"
const val ADDRESS_CANNOT_BE_EMPTY: String = "Address cannot be empty"
const val FORM_VALIDATION_FAILED: String = "Form validation failed"